<a href="https://colab.research.google.com/github/xegor4ikx/labs2/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1_Numpy_%D0%A1%D0%B8%D0%BB%D1%96%D0%BD_%D0%A4%D0%86%D0%A23_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [ ]:
# Код студента
import numpy as np
print(np.__version__)

2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [ ]:
# Код студента
arr = np.array([2, 4, 6, 8, 10])
print(arr)
print(type(arr))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
# Код студента
zeros = np.zeros(10)
ones = np.ones(8)
sevens = np.full(6, 7)
print(zeros)
print(ones)
print(sevens)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
# Код студента
nums = np.arange(1, 21)
evens = np.arange(2, 21, 2)
print(nums)
print(evens)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
arr = np.linspace(0, 1, 11)

print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
# Код студента
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
# Код студента
print("ndim:", matrix.ndim)
print("shape:", matrix.shape)
print("size:", matrix.size)
print("dtype:", matrix.dtype)

ndim: 2
shape: (3, 4)
size: 12
dtype: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
# Код студента
arr = np.array([1.2, 3.5, 5.7, 7.9])
int_arr = arr.astype(int)
print(int_arr)

[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
# Код студента
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[0])
print(arr[-1])
print(arr[2:6])
print(arr[::2])

10
80
[30 40 50 60]
[10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
# Код студента
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print(M[1, 2])     # елемент 7
print(M[1])        # другий рядок
print(M[:, 2])     # третій стовпець
print(M[-2:, :2])  # останні 2 рядки, перші 2 стовпці

7
[5 6 7 8]
[ 3  7 11]
[[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [ ]:
# Код студента
arr = np.arange(1, 16)
arr[5:10] = 0
print(arr)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [ ]:
# Код студента
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [ ]:
# Код студента
arr = np.array([4, 8, 15, 16, 23, 42])
print("сума:", arr.sum())
print("середнє:", arr.mean())
print("мінімум:", arr.min())
print("максимум:", arr.max())
print("медіана:", np.median(arr))
print("стандартне відхилення:", arr.std())

сума: 108
середнє: 18.0
мінімум: 4
максимум: 42
медіана: 15.5
стандартне відхилення: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [ ]:
# Код студента
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(M.sum())          # усі елементи
print(M.sum(axis=0))    # по стовпцях
print(M.sum(axis=1))    # по рядках
print(M.mean(axis=0))   # середнє по стовпцях

45
[12 15 18]
[ 6 15 24]
[4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [ ]:
# Код студента
arr = np.arange(1, 11)
print(np.square(arr))
print(np.sqrt(arr))
print(np.log(arr))

[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [ ]:
# Код студента
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])
print(arr[arr > 15])
print(arr[arr % 2 == 0])
print(arr[(arr >= 10) & (arr <= 30)])

[18 21 25 30 34]
[12 18 30 34]
[12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
arr[arr < 0] = 0
print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [ ]:
# Код студента
np.random.seed(42)
arr = np.random.randint(0, 101, 20)
print(arr)
print("> 50:", np.sum(arr > 50))
print("<= 50:", np.sum(arr <= 50))

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
> 50: 12
<= 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [ ]:
# Код студента
arr = np.arange(1, 25)
print(arr.reshape(4, 6).shape)
print(arr.reshape(6, 4).shape)
print(arr.reshape(2, 3, 4).shape)

(4, 6)
(6, 4)
(2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [ ]:
# Код студента
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.vstack((A, B)))  # вертикально
print(np.hstack((A, B)))  # горизонтально

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
# Код студента
M = np.arange(1, 13).reshape(3, 4)
f = M.flatten()
r = M.ravel()
print(f)
print(r)
print(np.array_equal(f, r))  # значення однакові
# flatten() завжди створює копію, ravel() за можливості повертає view на ті самі дані
print(np.shares_memory(M, f), np.shares_memory(M, r))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
True
False True


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
print(a + b)
print(a - b)
print(a * 3, b * 3)

[ 3  7 11]
[1 1 1]
[ 6 12 18] [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
# Код студента
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))
print(a @ b)

32
32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
# Код студента
v = np.array([3, 4])
norm = np.linalg.norm(v)
print(norm)
print(v / norm)  # одиничний вектор

5.0
[0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [ ]:
# Код студента
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
print(np.cross(a, b))

[0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [ ]:
# Код студента
a = np.array([1, 2])
b = np.array([2, 1])
cos = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(cos)
print(np.degrees(np.arccos(cos)))

0.7999999999999998
36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
# Код студента
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.T)
print(np.transpose(A))

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [ ]:
# Код студента
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
print(A * B)  # поелементний: множаться елементи на однакових позиціях
print(A @ B)  # матричний: кожен рядок A скалярно множиться на кожен стовпець B

[[2 0]
 [3 8]]
[[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
# Код студента
A = np.array([[4, 7], [2, 6]])
print(np.linalg.det(A))
A_inv = np.linalg.inv(A)
print(A_inv)
print(A @ A_inv)  # має вийти одинична матриця
print(np.allclose(A @ A_inv, np.eye(2)))

10.000000000000002
[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
True


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [ ]:
# Код студента
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print(x)  # [x, y]

[1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
# Код студента
E = np.eye(4)
M = np.random.randint(1, 10, (4, 4))
print(E)
print(M @ E)
print(np.array_equal(M @ E, M))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2. 5. 1. 6.]
 [9. 1. 3. 7.]
 [4. 9. 3. 5.]
 [3. 7. 5. 9.]]
True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [ ]:
# Код студента
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [ ]:
# Код студента
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([10, 20, 30])
print(A + v)
# v має форму (3,), NumPy "розтягує" його до (3, 3) і додає до кожного рядка A

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
A = np.array([[10, 20, 30], [20, 30, 40], [30, 40, 50]])
Z = (A - A.mean(axis=0)) / A.std(axis=0)
print(Z)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [ ]:
# Код студента
np.random.seed(42)
r1 = np.random.randint(1, 101, 10)
r2 = np.random.rand(3, 3)
r3 = np.random.randn(1000)
print(r1)
print(r2)
print("mean:", r3.mean(), "std:", r3.std())

[52 93 15 72 61 21 83 87 75 75]
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
mean: 0.02216865975826456 std: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [ ]:
# Код студента
grades = np.random.randint(0, 101, 30)
print(grades)
print("середня:", grades.mean())
print("медіана:", np.median(grades))
print("найвища:", grades.max(), "найнижча:", grades.min())
print("не менше 60:", np.sum(grades >= 60))
print("% не менше 90:", np.mean(grades >= 90) * 100)

[25  2 40 59 13 74 81 11 86 11 12 24 44 18 54 99 44  7 92 52 54 31 50 43
 81 69 17 82 21 36]
середня: 44.4
медіана: 43.5
найвища: 99 найнижча: 2
не менше 60: 8
% не менше 90: 6.666666666666667


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [ ]:
# Код студента
sales = np.array([[120, 150, 170, 160],
                  [80, 90, 100, 110],
                  [200, 180, 210, 230]])
print(sales.sum(axis=1))                  # по товарах
print(sales.sum(axis=0))                  # по місяцях
print("товар:", sales.sum(axis=1).argmax() + 1)
print("місяць:", sales.sum(axis=0).argmax() + 1)
print(sales.mean(axis=1))                 # середнє по товарах

[600 380 820]
[400 420 480 500]
товар: 3
місяць: 4
[150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [ ]:
# Код студента
M = np.random.randint(1, 21, (5, 5))
print(M)
print("головна діагональ:", np.trace(M))
print("побічна діагональ:", np.trace(np.fliplr(M)))
print("max рядків:", M.max(axis=1))
print("min стовпців:", M.min(axis=0))
M[M < M.mean()] = 0
print(M)

[[ 9  3 10 19  3]
 [15  1  7 12 17]
 [20  5  4 12 20]
 [18 17 19  9  4]
 [ 2  4  2 15  2]]
головна діагональ: 25
побічна діагональ: 38
max рядків: [19 17 20 19 15]
min стовпців: [2 1 2 9 2]
[[ 0  0 10 19  0]
 [15  0  0 12 17]
 [20  0  0 12 20]
 [18 17 19  0  0]
 [ 0  0  0 15  0]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [ ]:
# Код студента
X = np.array([[2, 4, 6], [1, 3, 5], [5, 7, 9]])
print(np.linalg.norm(X[0] - X[1]))
print(np.linalg.norm(X[0] - X[2]))
print(np.linalg.norm(X[1] - X[2]))

1.7320508075688772
5.196152422706632
6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [ ]:
# Код студента
M = np.random.randint(1, 10, (4, 4))
norms = np.linalg.norm(M, axis=1, keepdims=True)
M_norm = M / norms
print(norms.ravel())
print(M_norm)
print(np.linalg.norm(M_norm, axis=1))  # перевірка: усі 1

[10.48808848  7.61577311  9.94987437 11.53256259]
[[0.38138504 0.57207755 0.66742381 0.28603878]
 [0.3939193  0.7878386  0.3939193  0.26261287]
 [0.80403025 0.50251891 0.10050378 0.30151134]
 [0.69368798 0.34684399 0.60697698 0.17342199]]
[1. 1. 1. 1.]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [ ]:
# Код студента
A = np.array([[1, 2, 1], [2, 1, -1], [3, -1, 2]])
b = np.array([9, 8, 3])
x = np.linalg.solve(A, b)
print(x)
print(A @ x)
print(np.allclose(A @ x, b))

[ 2.22222222  3.44444444 -0.11111111]
[9. 8. 3.]
True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
